[growth]
n_atoms = 400 # Number of atoms to deposit
radius_offset = 3.61000 # Angstrom

[dynamics]
temperature = 1000 # Kelvin
timestep = 5 # Femtoseconds
steps = 300 # Number of steps
write_interval = 10