seed_filename = './seeds/Cu4631.xyz'
trajectory_filename = './output/dump.lammpstrj'
thermo_data_filename = './output/thermo.data'
temperature = 100 # Kelvin
timestep = 0.001 # Picoseconds
write_interval = 100
minimize_before_simulation = 'True'
lattice_constant = 3.6150
force_treshold = 0.1